import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const invsetors = [
    {
      name:"Jonathan Parker",
      price:"$3.60m",
      icon:"/arr.png",
      avatar:"/Rectangle 1.png"
    },
    {
      name:"Robert Laison",
      price:"$8.60m",
      icon:"/arrow_drop_down@2x.png",
      avatar:"/Rectangle 1 (2).png"
    }, {
      name:"Ricky Ponting",
      price:"$8.60m",
      icon:"/arr.png",
      avatar:"/Rectangle 1 (6).png"
    }, {
      name:"Michelle Ladson",
      price:"$8.00m",
      icon:"/arr.png",
      avatar:"/Rectangle 1 (5).png"
    }, {
      name:"Robert Laison",
      price:"$8.60m",
      icon:"/arrow_drop_down@2x.png",
      avatar:"/Rectangle 1 (1).png"
    }
  ]

  const bits = [
    {
      coin:"Bitcoin",
      avv:"btc",
      price:"$7,459.15",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },  {
      coin:"Litecoin",
      avv:"btc",
      price:"$599.9",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },  {
      coin:"Ethereum",
      avv:"eth",
      price:"$119.16",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },
  ]
  return (
    <>
      <Head>
        <title>Crypto Firm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/animation_500_l9g3hqe5 1.png" />
      </Head>

     
<div className='mt-[140px]'>
  <div className='flex md:justify-around flex-col md:flex-row px-3'>
    <div className='relative '>
    <Image src="/world 1.png" width={550} height={300}/>
    <div className='absolute md:top-[120px] left-0 top-[90px]'>
      <h1 className='md:text-6xl mb-[30px] text-5xl'>Crypto Currency <br/>Trading</h1>
      <p>Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange</p>
      <div className='mt-[40px]'><button className='bg-[#FD7000] text-white p-2 rounded-full w-[150px]'>Get Started</button></div>
    </div>

    </div>
    <div className='mt-[200px] md:mt-0'>
    <Image src="/animation_500_l9g3hqe5 1.png" width={530} height={300}/>
    </div>

  </div>

</div>

<div className='relative flex flex-col items-center justify-center'>
<Image src="/Group 7.png" width={2400} height={500}/>
<div className='absolute bottom-[30px] md:left-[150px]'>
  <h2 className='font-bold text-[#FD7000] text-2xl text-center md:text-left'>Our RoadMap</h2>
  <p className='w-[300px] text-center md:text-left'> speculating on Cryptocurrency price movements via a CFD trading </p>
</div>
</div>

<div className='flex items-center justify-center md:w-[80%] mx-auto mt-[100px]  '>
<Image src="/Group 4.png" width={2600} height={100}/>
</div>


<div className='flex items-center justify-center mt-[150px] relative mb-[50px]'>
<Image src="/Group 2283.png" width={1400} height={100}/>
<div className='absolute -top-[90px] md:left-[30%] '>
  <h3 className='text-center mb-[20px] '>How It Works</h3>
  <h2 className='font-bold text-[#FD7000] text-center text-4xl mb-[5px]'>Crypto ICO Platform</h2>
  <p className='md:w-[500px] text-center text-sm'> Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange </p>
  <div className=' flex items-center gap-[10px] justify-center mt-[30px] '>
    <p>Learn more </p>
    <div><Image src="/arrow_right_alt.png" width={20} height={100}/></div>
  </div>
</div>
</div>


<div className='mt-[100px]'>
  <div className='flex justify-around items-center flex-col md:flex-row'>
    <div>
    <Image src="/Line Chart.png" width={500} height={100}/>
    </div>

    <div>
      <h2 className='text-[#FD7000] mb-[30px]' style={{textDecoration:'underline'}}>Some Leads</h2>
      <div className='flex flex-col gap-[30px]'>
        {invsetors.map((item)=>{
          return(
            <div className='flex justify-around gap-[50px]'>
              <div className='flex gap-[20px] justify-center items-center'>
                <Image src={item.avatar} width={50} height={20}/>
                <h3 className='text-sm'>{item.name}</h3>
              </div>
              <div className='flex gap-[20px] items-center justify-center'>
              <Image src={item.icon} width={30} height={20}/>
                <h3 className='text-sm'>{item.price}</h3>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  </div>
</div>



<div className='flex items-center justify-center mt-[150px] relative'>
<Image src="/Group 2283.png" width={2400} height={100}/>
<div className='absolute -bottom-[50px] md:left-[150px] '>

  <h2 className='font-bold text-[#FD7000] text-4xl mb-[20px] text-center md:text-left'>Crypto ICO Platform</h2>
  <p className='md:w-[600px] md:text-left mb-[30px] text-center text-sm'> Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange </p>

  <div className=' flex items-center gap-[10px] justify-center md:text-left  '>
    <p>Learn more </p>
    <div><Image src="/arrow_right_alt.png" width={20} height={100}/></div>
  </div>

</div>
</div>
     
     <div className='mt-[140px] flex items-center justify-center'>
      <div className='grid grid-cols-1 md:grid-cols-3 gap-[20px]'>
        {bits.map((bit)=>{
          return (
            <div className='bg-gradient-to-b from-[#01406D] to-[#002138] w-[250px] h-[250px] flex flex-col justify-center items-center gap-[20px]'>
             <div className='flex items-center gap-[4px] justify-center'> <h1 className='text-2xl'>{bit.coin}</h1> <h3 className='text-sm text-[#486477]'>({bit.avv})</h3></div>
             <h2 className='text-2xl'>{bit.price}</h2>
             <div className='flex items-center text-sm gap-[4px]'>
             <Image src={bit.ar} width={20} height={100}/><p>{bit.percent}</p>
             </div>
             <div className='flex items-center text-sm gap-[7px] mt-[25px]'>
              <p>Learn More</p> <Image src={bit.icon} width={20} height={100}/>
             </div>

            </div>
          )
        })}
      </div>
     </div>
  

  <div className='relative'>
    <div className='absolute right-0 top-0 '>
    <Image src="/animation_500_l9ek1r4e 1.png" width={300} height={200}/>
    </div>
    
  </div>
    </>
  )
}
