import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const invsetors = [
    {
      name:"Jonathan Parker",
      price:"$3.60m",
      icon:"/arr.png",
      avatar:"/Rectangle 1.png"
    },
    {
      name:"Robert Laison",
      price:"$8.60m",
      icon:"/arrow_drop_down@2x.png",
      avatar:"/Rectangle 1 (2).png"
    }, {
      name:"Ricky Ponting",
      price:"$8.60m",
      icon:"/arr.png",
      avatar:"/Rectangle 1 (6).png"
    }, {
      name:"Michelle Ladson",
      price:"$8.00m",
      icon:"/arr.png",
      avatar:"/Rectangle 1 (5).png"
    }, {
      name:"Robert Laison",
      price:"$8.60m",
      icon:"/arrow_drop_down@2x.png",
      avatar:"/Rectangle 1 (1).png"
    }
  ]

  const bits = [
    {
      coin:"Bitcoin",
      avv:"BTC",
      price:"7,459",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },  {
      coin:"Bitcoin",
      avv:"BTC",
      price:"7,459",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },  {
      coin:"Bitcoin",
      avv:"BTC",
      price:"7,459",
      cta:"Learn More",
      icon:"/arrow_right_alt.png",
      percent:"79.9%",
      ar:"/arrow_drop_down@2x.png"
    },
  ]
  return (
    <>
      <Head>
        <title>Crypto Firm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
<div className='mt-[140px]'>
  <div className='flex justify-around'>
    <div className='relative '>
    <Image src="/world 1.png" width={500} height={300}/>
    <div className='absolute top-[120px] left-0'>
      <h1 className='text-6xl mb-[30px]'>Crypto Currency <br/>Trading</h1>
      <p>Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange</p>
      <div className='mt-[40px]'><button className='bg-[#FD7000] text-white p-2 rounded-full w-[150px]'>Get Started</button></div>
    </div>

    </div>
  <Image src="/animation_500_l9g3hqe5 1.png" width={500} height={300}/>
  </div>

</div>

<div className='relative'>
<Image src="/Group 7.png" width={1400} height={100}/>
<div className='absolute bottom-0 left-[150px]'>
  <h2 className='font-bold text-[#FD7000]'>Our RoadMap</h2>
  <p className='w-[300px]'> speculating on Cryptocurrency price movements via a CFD trading </p>
</div>
</div>

<div className='flex items-center justify-center w-[80%] mx-auto mt-[100px]'>
<Image src="/Group 4.png" width={1400} height={100}/>
</div>


<div className='flex items-center justify-center mt-[150px] relative'>
<Image src="/Group 2283.png" width={1400} height={100}/>
<div className='absolute -top-[90px] left-[30%]'>
  <h3 className='text-center mb-[20px] '>How It Works</h3>
  <h2 className='font-bold text-[#FD7000] text-center text-4xl mb-[5px]'>Crypto ICO Platform</h2>
  <p className='w-[500px] text-center'> Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange </p>

</div>
</div>


<div className='mt-[100px]'>
  <div className='flex justify-around items-center'>
    <div>
    <Image src="/Line Chart.png" width={500} height={100}/>
    </div>

    <div>
      <div className='flex flex-col gap-[30px]'>
        {invsetors.map((item)=>{
          return(
            <div className='flex justify-around gap-[50px]'>
              <div className='flex gap-[20px] justify-center items-center'>
                <Image src={item.avatar} width={50} height={20}/>
                <h3 className='text-sm'>{item.name}</h3>
              </div>
              <div className='flex gap-[20px] items-center justify-center'>
              <Image src={item.icon} width={30} height={20}/>
                <h3 className='text-sm'>{item.price}</h3>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  </div>
</div>



<div className='flex items-center justify-center mt-[150px] relative'>
<Image src="/Group 2283.png" width={1400} height={100}/>
<div className='absolute -bottom-[50px] left-[150px]'>

  <h2 className='font-bold text-[#FD7000] text-4xl mb-[20px]'>Crypto ICO Platform</h2>
  <p className='w-[600px] text-left mb-[30px]'> Cryptocurrency trading is the act of speculating on Cryptocurrency price movements via a CFD trading account,buying and selling the underlying coins via exchange </p>

  <div className=' flex items-center gap-[10px] '>
    <p>Learn more </p>
    <div><Image src="/arrow_right_alt.png" width={20} height={100}/></div>
  </div>

</div>
</div>
     
     <div className='mt-[100px] flex items-center justify-center'>
      <div className='flex gap-[20px]'>
        {bits.map((bit)=>{
          return (
            <div className='bg-[#01406D] w-[300px] h-[200px]'>
             <div> <h1>{bit.coin}</h1></div>
             <h2>{bit.price}</h2>
             <div>
             <Image src={bit.ar} width={20} height={100}/><p>{bit.percent}</p>
             </div>
             <div>
              <p>Learn More</p> <Image src={bit.icon} width={20} height={100}/>
             </div>

            </div>
          )
        })}
      </div>
     </div>
  

  <div className='relative'>
    <div className='absolute right-0 top-0'>
    <Image src="/animation_500_l9ek1r4e 1.png" width={300} height={200}/>
    </div>
    
  </div>
    </>
  )
}
